### ISSUE TITLE
Failed to execute script gp.exe

### ISSUE THREAD

**Issue by t0ffi** [Cleric-K/BlackboxToGPMF#2]
I tried to open gp.exe and Fatal error was detected with information: Failed to execute script gp.exe

Could somebody help because it is what I looking for year and now I cannot try it :(

**Comment by attilafustos** [comment]
Some PC's have trouble running the EXE,
Install python (and numpy) and run the python script directly.

**Comment by t0ffi** [comment]
I downloading now Anaconda pack for python and numphy. Which script I need to run directly? (sorry for dump question but I'm noob in this area)

**Comment by attilafustos** [comment]
join the Facebook group: FPV Stabilization tools. The script name is gp.py

**Comment by t0ffi** [comment]
Solved
